// Leaderboard client. Talks to the D1-backed Worker API.
// Same-origin when served by the Worker (tetrilaunch.com or the workers.dev
// fallback); absolute to the deployed Worker when running locally (vite dev),
// on a Cloudflare Pages preview (*.pages.dev branch deploys), or inside the
// Capacitor native shell. The Worker's /api responses are CORS-open
// (Access-Control-Allow-Origin: *), so the cross-origin cases need no proxy
// and share the production leaderboard.

const REMOTE = "https://tetrilaunch.com";

function apiBase(): string {
  const h = location.hostname;
  const servedByWorker =
    h === "tetrilaunch.com" || h === "www.tetrilaunch.com" || h.endsWith(".workers.dev");
  return servedByWorker ? "" : REMOTE;
}

export interface ScoreEntry {
  name: string;
  score: number;
  /** Bays reached (the run's depth). Still written and still returned; it is
   *  no longer what a score is RANKED by — see BoardKey. */
  level: number;
  lines: number;
  created_at: number;
}

/* -------------------------------------------------------------------------
 * BOARD KEYS
 *
 * Every score used to be posted with `level: 1` whatever Tier it was flown at,
 * so ten different games shared one ranking. That was survivable while only
 * one Tier was reachable at a time and stopped being so the moment a cleared
 * Tier could be replayed (docs/LONGEVITY.md).
 *
 * A board is a string key with its own namespace. The Worker validates the
 * SHAPE and not a list of known boards, so adding one is a client change
 * rather than a two-part release — see migrations/0002_boards.sql.
 * ---------------------------------------------------------------------- */

export type BoardKey = string;

/** Where every score written before boards existed lives, and where a client
 *  that predates them still posts. Never generated by this build; kept so the
 *  leaderboard screen can offer it rather than orphaning the old rankings. */
export const LEGACY_BOARD: BoardKey = "run";

/** Deep Run at a Tier — replays included, which is the point: a replay flies
 *  that Tier's own build budget (meta.ts's safeLoadout), so it competes on
 *  equal terms with the run that first cleared it. */
export function tierBoard(tier: number): BoardKey {
  return `tier:${Math.max(1, Math.floor(tier))}`;
}

export interface SubmitResult {
  ok: boolean;
  rank: number;
  scores: ScoreEntry[];
}

export async function fetchLeaderboard(
  board: BoardKey = LEGACY_BOARD,
  limit = 10,
): Promise<ScoreEntry[]> {
  try {
    const res = await fetch(
      `${apiBase()}/api/scores?board=${encodeURIComponent(board)}&limit=${limit}`,
    );
    if (!res.ok) return [];
    const data = (await res.json()) as { scores: ScoreEntry[] };
    return data.scores ?? [];
  } catch {
    return [];
  }
}

/** `level` is the run's DEPTH (bays reached), which the row carries for the
 *  board rows to show; `board` is what it is ranked against. They were the
 *  same argument once, which is exactly how every Tier ended up on one board. */
export async function submitScore(
  name: string,
  score: number,
  level: number,
  lines: number,
  board: BoardKey = LEGACY_BOARD,
): Promise<SubmitResult | null> {
  try {
    const res = await fetch(`${apiBase()}/api/scores`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name, score, level, lines, board }),
    });
    if (!res.ok) return null;
    return (await res.json()) as SubmitResult;
  } catch {
    return null;
  }
}
