// Re-download the self-hosted webfonts into public/fonts/.
//
// This is a ONE-OFF maintenance script, not a build step. The .woff2 files and
// the generated fonts.css are committed, because a build that reaches out to
// fonts.gstatic.com is exactly what self-hosting was meant to remove: the
// runtime fetch sent every player's IP to Google and made a cold launch depend
// on the network. Run this only to add a weight or pick up a font revision,
// then commit whatever changes.
//
// Google serves one @font-face per (family, weight, subset). We keep only the
// latin subset — the UI is uppercase English and the leaderboard sanitizes
// names to /[A-Z0-9 _-]/ (worker/index.ts), so no other subset can render. The
// unicode-range declarations are preserved verbatim so anything outside latin
// still falls back to the system stack instead of drawing tofu.
//
// Note that Orbitron and JetBrains Mono are variable fonts: Google emits three
// (resp. two) @font-face blocks that all point at the SAME file. This script
// detects that and downloads it once, so the weights cost no extra bytes.
import { mkdir, writeFile, readdir, unlink } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve, join } from "node:path";

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "public", "fonts");

// The exact families/weights the stylesheet asks for; see styles/tokens.css's
// --font-display / --font-ui / --font-mono / --font-pixel. Orbitron needs 900
// for --fw-black, which .display uses.
const QUERY =
  "family=Orbitron:wght@500;700;900" +
  "&family=Rajdhani:wght@500;600;700" +
  "&family=JetBrains+Mono:wght@500;700" +
  "&family=Press+Start+2P" +
  "&display=swap";

// css2 negotiates format by User-Agent: without a modern one it serves ttf.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const LATIN = "U+0000-00FF";

const slug = (family) => family.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

async function main() {
  const res = await fetch(`https://fonts.googleapis.com/css2?${QUERY}`, {
    headers: { "User-Agent": UA },
  });
  if (!res.ok) throw new Error(`css2 responded ${res.status} ${res.statusText}`);
  const css = await res.text();

  const faces = [];
  for (const block of css.split("@font-face").slice(1)) {
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? "normal";
    const url = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    if (!family || !weight || !url || !range) continue;
    if (!range.includes(LATIN)) continue; // non-latin subset — skip
    faces.push({ family, weight: Number(weight), style, url, range });
  }
  if (!faces.length) throw new Error("parsed no latin @font-face blocks — did css2 change format?");

  // One file may back several weights (variable fonts). Name it accordingly.
  const weightsPerUrl = new Map();
  for (const f of faces) {
    if (!weightsPerUrl.has(f.url)) weightsPerUrl.set(f.url, new Set());
    weightsPerUrl.get(f.url).add(f.weight);
  }
  const fileFor = new Map();
  for (const f of faces) {
    if (fileFor.has(f.url)) continue;
    const shared = weightsPerUrl.get(f.url).size > 1;
    fileFor.set(f.url, `${slug(f.family)}-${shared ? "variable" : f.weight}.woff2`);
  }

  await mkdir(OUT, { recursive: true });

  // Drop stale .woff2 first, so removing a weight from QUERY actually shrinks
  // the shipped bundle instead of leaving an orphan behind forever.
  const keep = new Set(fileFor.values());
  for (const stale of (await readdir(OUT)).filter((f) => f.endsWith(".woff2") && !keep.has(f))) {
    await unlink(join(OUT, stale));
    console.log(`  - ${stale} (stale)`);
  }

  for (const [url, name] of fileFor) {
    const font = await fetch(url, { headers: { "User-Agent": UA } });
    if (!font.ok) throw new Error(`${name}: ${font.status} ${font.statusText}`);
    const bytes = Buffer.from(await font.arrayBuffer());
    await writeFile(join(OUT, name), bytes);
    const backs = [...weightsPerUrl.get(url)].sort((a, b) => a - b).join("/");
    console.log(`  + ${name} (${(bytes.length / 1024).toFixed(1)} KB, weights ${backs})`);
  }

  // url()s are relative to this stylesheet, which keeps them working under
  // vite.config.ts's `base: "./"` and inside the Capacitor WebView alike.
  const header =
    "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n" +
    " *\n" +
    " * Self-hosted so the app never calls fonts.gstatic.com at runtime: that\n" +
    " * leaked the device IP to Google on every launch (a disclosable data flow\n" +
    " * on both stores) and made a cold start fail without a network.\n" +
    " *\n" +
    " * All four families are SIL Open Font License 1.1 — see OFL.txt.\n" +
    " */\n";

  const body = faces
    .map((f) =>
      [
        "@font-face {",
        `  font-family: '${f.family}';`,
        `  font-style: ${f.style};`,
        `  font-weight: ${f.weight};`,
        "  font-display: swap;",
        `  src: url('./${fileFor.get(f.url)}') format('woff2');`,
        `  unicode-range: ${f.range};`,
        "}",
      ].join("\n"),
    )
    .join("\n\n");

  await writeFile(join(OUT, "fonts.css"), `${header}\n${body}\n`);
  console.log(`✓ ${faces.length} @font-face rules over ${fileFor.size} files → public/fonts/`);
}

main().catch((err) => {
  console.error(`✗ font fetch failed: ${err.message}`);
  process.exit(1);
});
